### ISSUE TITLE
Create/use a Gemset specific to this project

### ISSUE THREAD

**Issue by emacadie** [cardoni/digital_schoolhouse#11]
I think we should make a new Gemset just for this project. I assume that you guys are using rvm.

To create:
rvm gemset create digital-schoolhouse

To use it:
rvm gemset use digital-schoolhouse

To go back to the default:
rvm gemset use global

**Comment by adamark** [comment]
Thanks, good call! I know me and Adam have already done that.

On Thu, Feb 23, 2012 at 5:03 PM, Eric MacAdie <
reply@reply.github.com

**Comment by emacadie** [comment]
What is the name of your Gemset? I would like to use the same name as you guys if possible.

I also think we should specify versions in the Gemfile, so instead of 
gem 'bcrypt-ruby', '~> 3.0.0'
we would have
gem 'bcrypt-ruby', '3.0.0'

**Comment by adamark** [comment]
My gemset is called @digital-schoolhouse, but gemsets are local so it
really doesn't matter, so long as it makes sense to you! There are certain
gems we should keep in version lockdown, but I'll dare to say bcrypt and a
few others should remain up to date unless you've heard/read otherwise.

On Thu, Feb 23, 2012 at 5:53 PM, Eric MacAdie <
reply@reply.github.com

**Comment by adamark** [comment]
Also to streamline the RVM gemset process, you should make a .rvmrc file, me and greg figured this out earlier. 
1. cd to our project and do    rvm --rvmrc --create 1.9.3@digital-schoolhouse      so long as you are using 1.9.3, if not, change that to your version. 2. Once running this command, open and new terminal and cd into the project, it will ask you if you trust this shell script to run, type yes, and from now on whenever you cd into that project it will ensure that you are using that version of ruby and that gemset. 3. Now type bundle install and you are good to go!

**Comment by awolfinthewind** [comment]
Adam M. had me do this on my machine, how bout you Greg?

:~A

**Comment by awolfinthewind** [comment]
Ok I did the .rvmrc thing. But how on earth did you figure that out?

**Comment by adamark** [comment]
I found it on the RVM site!

On Thu, Feb 23, 2012 at 11:18 PM, awolfinthewind <
reply@reply.github.com

**Comment by cardoni** [comment]
Adam, I think when you pushed last, you also pushed your .rvmrc file as well.  I added a line in the .gitignore file that will ignore all of our .rvmrc files so that they won't be pushed or pulled.  :)

**Comment by emacadie** [comment]
Updated the Gemfile
